name: E2

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # working-directory is ./E2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      working-directory: ./E2
      run: make install
    - name: compile files
      working-directory: ./E2
      run: make compile
    - name: test
      working-directory: ./E2
      run: make test



